"""add sync operations

Revision ID: 246171d7b8c5
Revises: 6f8f98191716
Create Date: 2026-10-02 04:20:07.722669
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "246171d7b8c5"
down_revision: str | None = "6f8f98191716"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_operations",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("operation_kind", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("result_number", sa.BigInteger(), nullable=False),
        sa.Column(
            "applied_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["sync_devices.id"],
            name=op.f("fk_sync_operations_device_id_sync_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_users.id"],
            name=op.f("fk_sync_operations_user_id_app_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_operations")),
        sa.UniqueConstraint("operation_id", name="sync_operation_id"),
    )
    op.create_index("ix_sync_operations_device_id", "sync_operations", ["device_id"], unique=False)
    op.create_index("ix_sync_operations_entity_id", "sync_operations", ["entity_id"], unique=False)
    op.create_index("ix_sync_operations_user_id", "sync_operations", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sync_operations_user_id", table_name="sync_operations")
    op.drop_index("ix_sync_operations_entity_id", table_name="sync_operations")
    op.drop_index("ix_sync_operations_device_id", table_name="sync_operations")
    op.drop_table("sync_operations")
    # ### end Alembic commands ###
