"""initial core schema

Revision ID: 41d5f60b9eea
Revises:
Create Date: 2026-09-28 01:29:59.818039
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "41d5f60b9eea"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_users",
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("login", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "admin",
                "mechanic",
                "tech_admin",
                name="user_role",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'mechanic', 'tech_admin')",
            name=op.f("ck_app_users_role_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_users")),
        sa.UniqueConstraint("login", name=op.f("uq_app_users_login")),
    )
    op.create_index("ix_app_users_role", "app_users", ["role"], unique=False)
    op.create_table(
        "clients",
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("phone_primary", sa.String(length=32), nullable=False),
        sa.Column("phone_secondary", sa.String(length=32), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "avito", "referral", "other", name="client_source", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("referred_by_client_id", sa.Uuid(), nullable=True),
        sa.Column("internal_mark", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "source IN ('avito', 'referral', 'other')", name=op.f("ck_clients_source_valid")
        ),
        sa.ForeignKeyConstraint(
            ["referred_by_client_id"],
            ["clients.id"],
            name=op.f("fk_clients_referred_by_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
    )
    op.create_index("ix_clients_full_name", "clients", ["full_name"], unique=False)
    op.create_index("ix_clients_phone_primary", "clients", ["phone_primary"], unique=False)
    op.create_table(
        "vehicles",
        sa.Column("license_plate", sa.String(length=32), nullable=False),
        sa.Column("vin", sa.String(length=17), nullable=True),
        sa.Column("brand", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("mileage", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "mileage IS NULL OR mileage >= 0", name=op.f("ck_vehicles_mileage_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
        sa.UniqueConstraint("vin", name=op.f("uq_vehicles_vin")),
    )
    op.create_index("ix_vehicles_brand_model", "vehicles", ["brand", "model"], unique=False)
    op.create_index("ix_vehicles_license_plate", "vehicles", ["license_plate"], unique=False)
    op.create_index("ix_vehicles_vin", "vehicles", ["vin"], unique=False)
    op.create_table(
        "client_vehicles",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("started_at", sa.Date(), nullable=True),
        sa.Column("ended_at", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_client_vehicles_ownership_dates_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_client_vehicles_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_client_vehicles_vehicle_id_vehicles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_vehicles")),
    )
    op.create_index(
        "ix_client_vehicles_client_vehicle",
        "client_vehicles",
        ["client_id", "vehicle_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_client_vehicles_client_vehicle", table_name="client_vehicles")
    op.drop_table("client_vehicles")
    op.drop_index("ix_vehicles_vin", table_name="vehicles")
    op.drop_index("ix_vehicles_license_plate", table_name="vehicles")
    op.drop_index("ix_vehicles_brand_model", table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index("ix_clients_phone_primary", table_name="clients")
    op.drop_index("ix_clients_full_name", table_name="clients")
    op.drop_table("clients")
    op.drop_index("ix_app_users_role", table_name="app_users")
    op.drop_table("app_users")
    # ### end Alembic commands ###
