"""add client referral integrity

Revision ID: 4706b728c103
Revises: dbe1c668c725
Create Date: 2026-09-30 12:46:59.348159
"""

from collections.abc import Sequence

revision: str = "4706b728c103"
down_revision: str | None = "dbe1c668c725"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
