"""add sync device foundation

Revision ID: 6f8f98191716
Revises: b2c7e4a19d50
Create Date: 2026-10-02 03:41:35.873000
"""

from collections.abc import Sequence

import sqlalchemy as sa


from alembic import op

revision: str = '6f8f98191716'
down_revision: str | None = 'b2c7e4a19d50'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_devices',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_key', sa.Uuid(), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=200), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], name=op.f('fk_sync_devices_user_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_devices')),
    sa.UniqueConstraint('user_id', 'device_key', name='user_device_key')
    )
    op.create_index('ix_sync_devices_last_seen_at', 'sync_devices', ['last_seen_at'], unique=False)
    op.create_index('ix_sync_devices_user_id', 'sync_devices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sync_devices_user_id', table_name='sync_devices')
    op.drop_index('ix_sync_devices_last_seen_at', table_name='sync_devices')
    op.drop_table('sync_devices')
    # ### end Alembic commands ###