"""add client archive and identity numbering

Revision ID: 9f2a6c1d4e70
Revises: 8c7d1e5a9b2f
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9f2a6c1d4e70"
down_revision: str | None = "8c7d1e5a9b2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE clients
        ALTER COLUMN client_number DROP DEFAULT
        """
    )

    op.execute(
        """
        DROP SEQUENCE IF EXISTS client_number_seq
        """
    )

    op.execute(
        """
        ALTER TABLE clients
        ALTER COLUMN client_number
        ADD GENERATED BY DEFAULT AS IDENTITY
        """
    )

    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('clients', 'client_number'),
            COALESCE(
                (SELECT MAX(client_number) FROM clients),
                1
            ),
            EXISTS(SELECT 1 FROM clients)
        )
        """
    )

    op.add_column(
        "clients",
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.add_column(
        "clients",
        sa.Column(
            "archive_reason",
            sa.String(length=32),
            nullable=True,
        ),
    )

    op.add_column(
        "clients",
        sa.Column(
            "archive_comment",
            sa.String(length=1000),
            nullable=True,
        ),
    )

    op.add_column(
        "clients",
        sa.Column(
            "archived_by_user_id",
            sa.Uuid(),
            nullable=True,
        ),
    )

    op.create_foreign_key(
        op.f("fk_clients_archived_by_user_id_app_users"),
        "clients",
        "app_users",
        ["archived_by_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    op.create_check_constraint(
        op.f("ck_clients_archive_reason_valid"),
        "clients",
        (
            "archive_reason IS NULL OR archive_reason IN ("
            "'no_longer_serviced', "
            "'created_by_mistake', "
            "'owner_request', "
            "'other'"
            ")"
        ),
    )

    op.create_check_constraint(
        op.f("ck_clients_archive_state_consistent"),
        "clients",
        (
            "("
            "archived_at IS NULL "
            "AND archive_reason IS NULL "
            "AND archive_comment IS NULL "
            "AND archived_by_user_id IS NULL"
            ") OR ("
            "archived_at IS NOT NULL "
            "AND archive_reason IS NOT NULL "
            "AND archived_by_user_id IS NOT NULL"
            ")"
        ),
    )

    op.create_index(
        "ix_clients_archived_at",
        "clients",
        ["archived_at"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_clients_archived_at",
        table_name="clients",
    )

    op.drop_constraint(
        op.f("ck_clients_archive_state_consistent"),
        "clients",
        type_="check",
    )

    op.drop_constraint(
        op.f("ck_clients_archive_reason_valid"),
        "clients",
        type_="check",
    )

    op.drop_constraint(
        op.f("fk_clients_archived_by_user_id_app_users"),
        "clients",
        type_="foreignkey",
    )

    op.drop_column(
        "clients",
        "archived_by_user_id",
    )

    op.drop_column(
        "clients",
        "archive_comment",
    )

    op.drop_column(
        "clients",
        "archive_reason",
    )

    op.drop_column(
        "clients",
        "archived_at",
    )

    op.execute(
        """
        ALTER TABLE clients
        ALTER COLUMN client_number
        DROP IDENTITY IF EXISTS
        """
    )

    op.execute(
        """
        CREATE SEQUENCE client_number_seq
        AS BIGINT
        START WITH 1
        INCREMENT BY 1
        NO CYCLE
        """
    )

    op.execute(
        """
        SELECT setval(
            'client_number_seq',
            COALESCE(
                (SELECT MAX(client_number) FROM clients),
                1
            ),
            EXISTS(SELECT 1 FROM clients)
        )
        """
    )

    op.execute(
        """
        ALTER SEQUENCE client_number_seq
        OWNED BY clients.client_number
        """
    )

    op.execute(
        """
        ALTER TABLE clients
        ALTER COLUMN client_number
        SET DEFAULT nextval('client_number_seq'::regclass)
        """
    )
